language: python
python:
- '2.7'
install: pip install -r requirements.txt
script: python tests.py
deploy:
  provider: heroku
  api_key:
    secure: ePYeuFOuEkApAYi77ir+zfmqd/sd6prqFN0GoDeBAMbrmPyKsswIA0TysrJM9eLVSm/T/xHIinjJ4XTF1JB5iidL9ASCgbgzLrMnTDYGAu5Y7fqvXsqQqu5+Sm9kdiqaXHICPrD4xpWde7sFviiZuWP3mUY/qWd3ry45sLNcjZw=
  app: hat-cats
  on:
    repo: joshsamara/demo_site
