language: python
python:
- '2.7'
install: pip install -r requirements.txt
script: python tests.py
deploy:
  provider: heroku
  api_key:
    secure: L9cQXhOno4YzI5cibVyU4KQUt1KENVYjIufCAw21+LMQ+Spg4t4fRi1EVLnFvqe/5WdpoowjK78dpoESPWnzBtlKveKhbXCln/1rFoYz8T6qT4puC15ljUlPYfmhYpJY4mi21ZtW5yE5blYQ57kYZRKTfUo+n9ZgwGJrMvtV0nM=
  app: hat-cats
  on:
    repo: joshsamara/demo_site
